# Generated by Django 5.2.6 on 2025-09-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('diagram', models.TextField()),
            ],
        ),
    ]
